export const works = [
  {
    year: "2018",
    kind: "电视剧",
    title: "芸汐传",
    role: "韩芸汐",
    note: "从偶像舞台走向古装大女主的重要节点，也以《叹云兮》延展了角色的音乐记忆。",
    source: "https://www.iq.com/play/legend-of-yun-xi-2018-19rrhl3t7l?lang=zh_cn",
    image: "/images/works/yunxi.webp",
    platform: "iQIYI",
    width: 1920,
    height: 1080,
  },
  {
    year: "2019",
    kind: "电视剧",
    title: "新白娘子传奇",
    role: "白素贞",
    note: "以新一代视角重新演绎经典白蛇故事，在古典气质与当代表达之间寻找平衡。",
    source: "https://www.iq.com/play/the-legend-of-white-snake-2019-2c3s5z48ijx?lang=zh_cn",
    image: "/images/works/white-snake.webp",
    platform: "iQIYI",
    width: 1920,
    height: 1080,
  },
  {
    year: "2019",
    kind: "音乐单曲",
    title: "恋爱告急",
    role: "演唱",
    note: "轻快明亮的个人单曲，成为她离开团体舞台之后极具辨识度的流行音乐作品。",
    source: "https://music.apple.com/cn/album/%E6%81%8B%E7%88%B1%E5%91%8A%E6%80%A5-single/1703179030",
    image: "/images/works/love-emergency.jpg",
    imageFit: "contain",
    platform: "APPLE MUSIC",
    width: 1200,
    height: 1200,
  },
  {
    year: "2023",
    kind: "电视剧",
    title: "花戎",
    role: "魏枝 / 司马忘月 / 魔后",
    note: "在仙侠叙事中呈现多重人物状态，让角色的成长、选择与宿命彼此映照。",
    source: "https://www.iqiyi.com/a_188g3fn6fl1.html",
    image: "/images/works/beauty-of-resilience.webp",
    platform: "iQIYI",
    width: 1920,
    height: 1080,
  },
  {
    year: "2024",
    kind: "电视剧",
    title: "仙剑四",
    role: "韩菱纱",
    note: "饰演机敏灵动的韩菱纱，并演唱角色主题曲《如纱》。",
    source: "https://www.iqiyi.com/a_dwo684rau1.html",
    image: "/images/works/sword-and-fairy-4.webp",
    platform: "iQIYI",
    width: 1920,
    height: 1080,
  },
  {
    year: "2024",
    kind: "电视剧",
    title: "花间令",
    role: "杨采薇 / 上官芷",
    note: "古装、爱情与探案交织的作品，以双重身份带出人物关系的悬念。",
    source: "https://v.youku.com/v_nextstage/id_ffaac0420f0042b9b1e1.html",
    image: "/images/works/in-blossom.jpg",
    platform: "YOUKU",
    width: 1366,
    height: 768,
  },
  {
    year: "2026",
    kind: "电视剧",
    title: "月鳞绮纪",
    role: "露芜衣",
    note: "饰演九尾狐露芜衣，于 2026 年 4 月上线，是她最新的荧幕章节。",
    source: "https://www.youku.tv/v/v_show/id_XNjUyODI3NDY1Mg%3D%3D.html?s=ddad446e1d6645cdb814",
    image: "/images/works/moonlit-reunion.jpg",
    platform: "YOUKU",
    width: 1366,
    height: 768,
  },
];

export const timeline = [
  {
    year: "1994",
    title: "生于四川遂宁",
    text: "6 月 18 日出生。舞蹈、小提琴与舞台训练，构成她日后演员与歌手双线发展的起点。",
  },
  {
    year: "2013",
    title: "剧场初见",
    text: "作为 SNH48 二期生，以《剧场女神》公演正式出道，从小剧场开始积累舞台经验。",
  },
  {
    year: "2014—17",
    title: "四次总选，两度登顶",
    text: "四届年度总选举排名依次为第 4、第 2、第 1、第 1；2017 年晋升明星殿堂。",
  },
  {
    year: "2016",
    title: "从舞台走向镜头",
    text: "出演《九州·天空城》中的雪飞霜，并推出首张个人 EP《每一天》，开启个人作品线。",
  },
  {
    year: "2017",
    title: "成立个人工作室",
    text: "12 月 15 日起以个人艺人身份继续发展，表演与音乐成为并行的两条创作路径。",
  },
  {
    year: "2018—24",
    title: "角色不断生长",
    text: "从韩芸汐、白素贞到韩菱纱与上官芷，在古装、仙侠与探案叙事中建立荧幕辨识度。",
  },
  {
    year: "2026",
    title: "新的荧幕章节",
    text: "《月鳞绮纪》上线，饰演九尾狐露芜衣；表演与音乐仍在持续交汇。",
  },
];

export const gallery = [
  {
    src: "/images/ju-birthday-2021.jpg",
    alt: "鞠婧祎身着礼服坐在书房沙发上阅读",
    caption: "书房肖像 · 2021",
    file: "https://commons.wikimedia.org/wiki/File:Ju_Jing_Yi_27th.jpg",
    className: "galleryLead",
    width: 1800,
    height: 1350,
  },
  {
    src: "/images/ju-portrait-02.jpg",
    alt: "鞠婧祎在舞台上手持麦克风微笑",
    caption: "舞台时刻 · 2017",
    file: "https://commons.wikimedia.org/wiki/File:%E9%9E%A0%E5%A9%A7%E7%A5%8E_(2).jpg",
    className: "galleryTall",
    width: 1174,
    height: 1800,
  },
  {
    src: "/images/ju-portrait-04.jpg",
    alt: "鞠婧祎在舞台灯光下的半身肖像",
    caption: "聚光灯下 · 2017",
    file: "https://commons.wikimedia.org/wiki/File:%E9%9E%A0%E5%A9%A7%E7%A5%8E_(4).jpg",
    className: "galleryPortrait",
    width: 1320,
    height: 1800,
  },
  {
    src: "/images/ju-election-2015.jpg",
    alt: "鞠婧祎与 SNH48 成员在舞台上演出",
    caption: "SNH48 舞台 · 2015",
    file: "https://commons.wikimedia.org/wiki/File:SNH48_%E7%AC%AC%E4%BA%8C%E5%B1%8A%E6%80%BB%E9%80%89%E4%B8%BE_10.jpg",
    className: "galleryWide",
    width: 1800,
    height: 1350,
  },
  {
    src: "/images/ju-portrait-03.jpg",
    alt: "鞠婧祎身着黄色舞台服装的全身照",
    caption: "舞台造型 · 2017",
    file: "https://commons.wikimedia.org/wiki/File:%E9%9E%A0%E5%A9%A7%E7%A5%8E_(3).jpg",
    className: "galleryPortrait galleryCropLow",
    width: 1264,
    height: 1800,
  },
  {
    src: "/images/ju-portrait-05.jpg",
    alt: "鞠婧祎在紫色舞台灯光中的近景肖像",
    caption: "光影近景 · 2017",
    file: "https://commons.wikimedia.org/wiki/File:%E9%9E%A0%E5%A9%A7%E7%A5%8E_(5).jpg",
    className: "gallerySquare",
    width: 1257,
    height: 1800,
  },
];

export const sources = [
  ["SNH48 官方履历", "https://www.snh48.com/html/snh/allnews/zixun/201712/4355.html"],
  ["Apple Music 艺人页", "https://music.apple.com/us/artist/%E9%9E%A0%E5%A9%A7%E7%A5%8E/1252617058?l=zh-Hans-CN"],
  ["1905 电影网人物资料", "https://m.1905.com/m/star/3157585/"],
  ["iQIYI 演员资料", "https://www.iq.com/actor-info/ju-jing-yi-cecily-kiku-223740805?lang=zh_cn"],
];

